### ISSUE TITLE
notifyDataSetChanged() not working

### ISSUE THREAD

**Issue by danponce** [thoughtbot/expandable-recycler-view#39] opened 2017-01-03 19:25 UTC
Tried this method on the adapter and got an exception. I just add a new Genre to the simple expand sample app.

**Comment by sudhanshunathmishra** [comment] 2017-01-27 01:32
I am getting the same error. Every time I adding or deleting an object to/from the underlying list, it crashes with " java.lang.ArrayIndexOutOfBoundsException: length=1; index=1" in ExpandableList.numberOfVisibleItemsInGroup

**Comment by mandybess** [comment] 2017-01-27 01:36
The current version of the library does not support adding / removing items from list of `ExpandableGroup` that you instantiated the adapter with. 

We hope to have this feature out in the next relase

**Comment by mandybess** [comment] 2017-01-27 01:37
Duplicate of #27

**Closed by mandybess** 2017-01-27 01:37 UTC
